#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(
    CDPATH=''
    cd -- "$(dirname -- "$0")/.." && pwd
)"

CLI="$ROOT_DIR/dndistress"
OUT="$ROOT_DIR/README.md"

TOPICS_FALLBACK="general usage topics info description runtime resolver install uninstall show version binary burst column custom directory duration file format local location maximum output port qps remote seconds top type url verbosity"

if [ ! -f "$CLI" ]; then
    printf '%s\n' "error: CLI not found at $CLI" >&2
    exit 1
fi

if [ ! -x "$CLI" ]; then
    chmod +x "$CLI"
fi

read_cli_var() {
    key="$1"
    awk -F= -v key="$key" '
        $0 ~ "^[[:space:]]*" key "[[:space:]]*=" {
            v=$2
            sub(/^[[:space:]]+/, "", v)
            sub(/[[:space:]]+$/, "", v)
            gsub(/^["\047]|["\047]$/, "", v)
            print v
            exit
        }
    ' "$CLI"
}

read_generated_at() {
    date -u '+%Y-%m-%d %H:%M:%S UTC'
}

DOC_VERSION="$(read_cli_var VERSION)"
DOC_AUTHOR="$(read_cli_var AUTHOR_NAME)"
DOC_COPYRIGHT_YEAR="$(read_cli_var COPYRIGHT_YEAR)"
DOC_CONTACT="$(read_cli_var CONTACT)"
DOC_LICENSE="$(read_cli_var LICENSE)"

if [ -z "${DOC_VERSION:-}" ]; then
    DOC_VERSION="unknown"
fi

if [ -z "${DOC_AUTHOR:-}" ]; then
    DOC_AUTHOR="unknown"
fi

if [ -z "${DOC_COPYRIGHT_YEAR:-}" ]; then
    DOC_COPYRIGHT_YEAR="unknown"
fi

if [ -z "${DOC_CONTACT:-}" ]; then
    DOC_CONTACT="unknown"
fi

if [ -z "${DOC_LICENSE:-}" ]; then
    DOC_LICENSE="unknown"
fi

GENERATED_AT="$(read_generated_at)"

mkdir -p "$(dirname -- "$OUT")"

run_help() {
    topic="$1"
    (
        cd -- "$ROOT_DIR"
        if [ "$topic" = "general" ]; then
            ./dndistress --help
        else
            ./dndistress --help "$topic"
        fi
    )
}

discover_topics() {
    (
        cd -- "$ROOT_DIR"
        ./dndistress --help topics
    ) | awk '
        /^[[:space:]]+General:/  { sect=1; next }
        /^[[:space:]]+Commands:/ { sect=1; next }
        /^[[:space:]]+Options:/  { sect=1; next }
        /^[[:space:]]*Aliases accepted:/ { sect=0; next }

        sect && /^[[:space:]]{4}[[:alnum:] _-]+$/ {
            for (i=1; i<=NF; i++) {
                if ($i ~ /^[a-z][a-z0-9-]*$/) print $i
            }
        }
    ' | awk '!seen[$0]++' | grep -v '^help$' || true
}

TOPICS="$(discover_topics)"
if [ -z "$TOPICS" ]; then
    TOPICS="$TOPICS_FALLBACK"
fi

emit_topic() {
    topic="$1"
    printf '\n## %s\n\n' "$topic"
    printf '%s\n' '```text'
    run_help "$topic"
    printf '%s\n' '```'
}

{
cat <<EOF
# DNdistresS

\`\`\`text
           _____   _____       _ _                             _____
          |  __ \ |  __ \     | (_)       _                   / ____)
          | |  \ \| |  \ \  __| |_  ___ _| |_  ____ _____  __( (____
          | |   | | |   | |/ _  | |/___)_   _)/ ___) ___ |/___)____ \\
          | |__/ /| |   | | |_| | |___ | | |_| |   | ____|___ |____) )
          |_____/ |_|   |_|\____|_(___/   \__)_|   |_____(___(______/

    Version: $DOC_VERSION
    Contact: $DOC_CONTACT
    License: $DOC_LICENSE

    DNdistresS Copyright (C) $DOC_COPYRIGHT_YEAR $DOC_AUTHOR

    This program comes with ABSOLUTELY NO WARRANTY; for details type 'show w'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type 'show c' for details.
\`\`\`

---

## Index
EOF

    for t in $TOPICS; do
        printf '%s\n' "- [$t](#$t)"
    done

    for t in $TOPICS; do
        emit_topic "$t"
    done

    printf '\n---\n\n> Generated by `%s` on %s.\n' "$0" "$GENERATED_AT"
} > "$OUT"

printf '%s\n' "generated: $OUT"
